DROP VIEW public.view_invtran;
CREATE VIEW public.view_invtran
(REATE VIEW public.view_invtran
  idno,assettype,strno,"desc",price,gcode,memo1, engno, regno, regprov, regdate, regexp, typedesc, modeldesc, colordesc, manuyr, 
  milert, insurecode, insuredate, insureexp, insurecomcode, prbcode, prbdate, prbexp, prbcomcode, area1, area2, area3, area4,yr, 
  landdate, homeagee, insuredate, insureexp, insurecomcode, prbcode, prbdate, prbexp, prbcomcode, area1, area2, area3, area4,yr, 
) landdate, homeagee, insuredate, insureexp, insurecomcode, prbcode, prbdate, prbexp, prbcomcode, area1, area2, area3, area4,yr, 
ASlanddate, homeagee, insuredate, insureexp, insurecomcode, prbcode, prbdate, prbexp, prbcomcode, area1, area2, area3, area4,yr, 
SELECT a.idno, a.assettype, a.strno, a."desc", a.price, a.gcode, a.memo1, b.engno, b.regno, b.regprov,1, area2, area3, area4,yr, 
       b.regdate, b.regexp, b.typedesc, b.modeldesc, b.colordesc, b.manuyr, b.milert, b.insurecode, v,1, area2, area3, area4,yr, 
       b.insuredate, b.insureexp, b.insurecomcode, b.prbcode, b.prbdate, b.prbexp, b.prbcomcode, 0 as area1,a2, area3, area4,yr, 
       0 as area2, 0 as area3, 0 as area4, null as landdate, 0 as homeageb.prbexp, b.prbcomcode, 0 as area1,a2, area3, area4,yr, 
FROM   invtran a left join assetdetail1 b on a.strno = b.strno as homeageb.prbexp, b.prbcomcode, 0 as area1,a2, area3, area4,yr, 
WHERE  a.assettype = 1join assetdetail1 b on a.strno = b.strno as homeageb.prbexp, b.prbcomcode, 0 as area1,a2, area3, area4,yr, 
UNION ALLassettype = 1join assetdetail1 b on a.strno = b.strno as homeageb.prbexp, b.prbcomcode, 0 as area1,a2, area3, area4,yr, 
SELECT a.idno, a.assettype, a.strno, a."desc", a.price, a.gcode, a.memo1, COALESCE(b.engno,''), COALESCE(b.pageno,''), b.POSITION,
       null as regdate, null as regexp, b.landno, b.survey, b.tumbcode, 0 as manuyr, 0 as milert, ALESCE(b.pageno,''), b.POSITION,
       b.aumpcode, null as insuredate, null as insureexp, b.provcode, '', null as prbdate, null as prbexp, pageno,''), b.POSITION,
       '', b.area1, b.area2, b.area3, 0 as area4, b.landdate, 0 as homeagenull as prbdate, null as prbexp, pageno,''), b.POSITION,
FROM   invtran a left join assetdetail2 b on a.strno = b.strno0 as homeagenull as prbdate, null as prbexp, pageno,''), b.POSITION,
WHERE  a.assettype = 2join assetdetail2 b on a.strno = b.strno0 as homeagenull as prbdate, null as prbexp, pageno,''), b.POSITION,
UNION ALLassettype = 2join assetdetail2 b on a.strno = b.strno0 as homeagenull as prbdate, null as prbexp, pageno,''), b.POSITION,
SELECT a.idno, a.assettype, a.strno, a."desc", a.price, a.gcode, a.memo1, COALESCE(b.engno,''), COALESCE(b.address,''), b.location,
       null as regdate, null as regexp, b.nearby, b.typehome, b.typehome, 0 as manuyr, 0 as milert, ESCE(b.address,''), b.location,
       '', null as insuredate, null as insureexp, '', '', null as prbdate, null as prbexp,  milert, ESCE(b.address,''), b.location,
       '', b.area1, b.area2, b.area3, b.area4, null as landdate, b.homeage null as prbexp,  milert, ESCE(b.address,''), b.location,
FROM   invtran a left join assetdetail3 b on a.strno = b.strnoe, b.homeage null as prbexp,  milert, ESCE(b.address,''), b.location,
WHERE  a.assettype = 3join assetdetail3 b on a.strno = b.strnoe, b.homeage null as prbexp,  milert, ESCE(b.address,''), b.location,
UNION ALLassettype = 3join assetdetail3 b on a.strno = b.strnoe, b.homeage null as prbexp,  milert, ESCE(b.address,''), b.location,
SELECT a.idno, a.assettype, a.strno, a."desc", a.price, a.gcode, a.memo1, '' as engno,'' as regno, '' as regprov,s,''), b.location,
       null as regdate, null as regexp, '' as typedesc, '' as modeldesc, '' as colordesc, 0 as manuyr, 0 as milert, '' as insurecode, 
       null as insuredate, null as insureexp, '' as insurecomcode, '' as prbcode, null as prbdate, null as prbexp, '' as prbcomcode, 0 as area1,
       0 as area2, 0 as area3, 0 as area4, null as landdate, 0 as homeageprbcode, null as prbdate, null as prbexp, '' as prbcomcode, 0 as area1,
FROM   invtran a left join assetdetail1 b on a.strno = b.strno as homeageprbcode, null as prbdate, null as prbexp, '' as prbcomcode, 0 as area1,
WHERE  a.assettype = 4;oin assetdetail1 b on a.strno = b.strno as homeageprbcode, null as prbdate, null as prbexp, '' as prbcomcode, 0 as area1,
